### ISSUE TITLE
Bad sed commands used for mail passwords

### ISSUE THREAD

**Issue by StoneISStephan** [Tozzje/da2plesk#2]
When running the hack to dump mail passwords, I noticed that your sed commands deletes [(),] and IP addresses.
I found users to have these matches in their actual passwords. 

I suggest using:

grep -h "is a match" /var/log/maillog{.{99..1},} 2>/dev/null | grep "passwd-file" | awk '{print $7 " " $8}' | sed 's#passwd-file(##g;s#)$##g;s#,.*): MD5-CRYPT(# #g' | sort | uniq > /root/emailpws

As these sed commands only carve out the dovecot strings and the IP's at the correct places, never the password itself, regardless of which characters or sequences it holds.

**Comment by Tozzje** [comment]
I will adapt the readme. Thanks. I did have to change $7 and $8 to $8 and $9 in my case. Also, my logs were not in /var/log/maillog but in /var/log/mail.log. Could be because of a different distribution.
